const DATA={players:[],clubs:[],associations:[],tournaments:[],results:[],rounds:[],drl:[],dmv:[]};
let state={view:"players",q:"",detail:null};
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const SOURCES={players:"data/players.csv",clubs:"data/clubs.csv",associations:"data/associations.csv",tournaments:"data/tournaments.csv",results:"data/results.csv",rounds:"data/rounds.csv",dmv:"data/dmv_entries.csv"};
const DRL_SHARDS=Array.from({length:8},(_,i)=>`data/drl_entries_${String(i+1).padStart(2,"0")}.json`);
async function load(key){try{const r=await fetch(SOURCES[key],{cache:"no-store"});if(!r.ok)throw 0;DATA[key]=parseCSV(await r.text())}catch(e){DATA[key]=[]}}
async function loadDRL(){let all=[],loaded=0;for(const url of DRL_SHARDS){try{const r=await fetch(url,{cache:"no-store"});if(!r.ok)continue;const x=await r.json();all.push(...(Array.isArray(x)?x:(x.rows||[])));loaded++}catch(e){}}if(loaded){DATA.drl=all;return}try{const r=await fetch("data/drl_entries.csv",{cache:"no-store"});if(r.ok)DATA.drl=parseCSV(await r.text())}catch(e){DATA.drl=[]}}
function parseCSV(t){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++;continue}if(c==='"'){quoted=!quoted;continue}if(c===','&&!quoted){row.push(cell);cell="";continue}if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&n==="\n")i++;row.push(cell);cell="";continue}cell+=c}if(cell||row.length){row.push(cell);if(row.some(x=>x.trim()))rows.push(row)}if(!rows.length)return[];const h=rows.shift().map(x=>x.trim());return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??"").trim()])))}
function val(o,...keys){for(const k of keys)if(o?.[k]!=null&&o[k]!=="")return o[k];return""}
function ident(o){return val(o,"player_id","club_id","association_id","tournament_id","result_id","round_id","drl_entry_id","dmv_entry_id","id")}
function label(o){return val(o,"name","canonical_name","player_name","club_name","tournament_name","association_name","original_name","normalized_name")||ident(o)}
function norm(s){return String(s??"").toLocaleLowerCase("de-DE").trim()}
function matches(o){const q=norm(state.q);return!q||Object.values(o).some(v=>norm(v).includes(q))}
function findById(view,key){return(DATA[view]||[]).find(o=>String(ident(o))===String(key))}
function related(view,obj){const keys={players:["player_id","pass_number"],clubs:["club_id"],associations:["association_id"],tournaments:["tournament_id"],results:["result_id","player_id","tournament_id"],rounds:["round_id","result_id","player_id"],drl:["drl_entry_id","player_id","pass_number"],dmv:["dmv_entry_id","player_id","pass_number"]};const source=keys[state.view]||[];const target=keys[view]||[];return(DATA[view]||[]).filter(x=>source.some(k=>obj?.[k]!==undefined&&obj[k]!==""&&target.some(t=>String(x?.[t]??"")===String(obj[k]))))}
function link(view,key,text){return'<button class="link" onclick="openItem('+JSON.stringify(view)+','+JSON.stringify(String(key))+')">'+esc(text||key)+"</button>"}
function setView(v){state.view=v;state.detail=null;state.q="";$("#search").value="";render()}
function openItem(v,k){state.view=v;state.detail=k;state.q="";$("#search").value="";render()}
function renderStats(){const defs=[["players","Spieler"],["clubs","Vereine"],["tournaments","Turniere"],["results","Ergebnisse"]];$("#stats").innerHTML=defs.map(([k,l])=>'<button class="stat" onclick="setView(\''+k+'\')"><b>'+DATA[k].length.toLocaleString("de-DE")+'</b><span>'+l+"</span></button>").join("")}
function cell(o,k){const v=val(o,k);if(!v)return"";const map={player_id:"players",club_id:"clubs",current_club_id:"clubs",association_id:"associations",current_association_id:"associations",tournament_id:"tournaments",result_id:"results"};const target=map[k];return target&&findById(target,v)?link(target,v,label(findById(target,v))):esc(v)}
function resultRows(player){return DATA.results.filter(r=>String(r.player_id||"")===String(player.player_id||"")||String(r.pass_number||"")===String(player.pass_number||""))}
function roundRows(resultIds){const ids=new Set(resultIds.map(String));return DATA.rounds.filter(r=>ids.has(String(r.result_id||"")))}
function playerHistory(p){const rs=resultRows(p), rr=roundRows(rs.map(r=>r.result_id).filter(Boolean));const clubs=[...new Map(rs.map(r=>{const id=r.club_id||r.current_club_id||"";return[id,{id,name:label(findById("clubs",id)||r)}]}).filter(([id])=>id)).values()];const ts=[...new Map(rs.map(r=>{const id=r.tournament_id||"";return[id,{id,name:label(findById("tournaments",id)||r)}]}).filter(([id])=>id)).values()];const drl=DATA.drl.filter(d=>String(d.player_id||"")===String(p.player_id||"")||String(d.pass_number||"")===String(p.pass_number||""));return{rs,rr,clubs,ts,drl}}
function section(title,body){return'<div class="history-section"><div class="history-title">'+esc(title)+'</div>'+body+'</div>'}
function compactLinks(view,items){return items.length?items.slice(0,30).map(x=>link(view,x.id,x.name)).join(" · "):'<span class="muted">Keine Daten verknüpft</span>'}
function playerDetail(p){const h=playerHistory(p);let out='<div class="player-hero"><div><div class="eyebrow">SPIELERAKTE</div><h2>'+esc(label(p))+'</h2><div class="hero-meta">'+(p.pass_number?'Passnummer: '+esc(p.pass_number):'Passnummer nicht hinterlegt')+'</div></div><div class="hero-status">'+esc(p.identity_status||"zugeordnet")+'</div></div>';out+='<div class="cards">';for(const [k,v] of Object.entries(p).filter(([,v])=>v!=="").slice(0,12))out+='<div class="card"><small>'+esc(k)+'</small><strong>'+esc(v)+'</strong></div>';out+='</div>';out+='<div class="history-grid">';out+=section("Vereinsgeschichte",'<div class="history-links">'+compactLinks("clubs",h.clubs)+'</div>');out+=section("Turnierteilnahmen",'<div class="history-stat"><b>'+h.ts.length.toLocaleString("de-DE")+'</b> verknüpfte Turniere</div><div class="history-links">'+compactLinks("tournaments",h.ts)+'</div>');out+=section("Ergebnisse",'<div class="history-stat"><b>'+h.rs.length.toLocaleString("de-DE")+'</b> Ergebnisse</div><div class="history-links">'+h.rs.slice(0,20).map(r=>link("results",r.result_id,label(findById("tournaments",r.tournament_id)||r))).join(" · ")+'</div>');out+=section("Rundenergebnisse",'<div class="history-stat"><b>'+h.rr.length.toLocaleString("de-DE")+'</b> Runden</div><div class="history-links">'+h.rr.slice(0,20).map(r=>esc((r.round_no||"Runde")+" · "+(r.score||""))).join(" · ")+'</div>');out+=section("DRL-Verlauf",'<div class="history-stat"><b>'+h.drl.length.toLocaleString("de-DE")+'</b> DRL-Einträge</div><div class="history-links">'+h.drl.slice(0,20).map(d=>link("drl",d.drl_entry_id,(d.list_date||"")+" · Rang "+(d.rank||"")+" · "+(d.value||""))).join(" · ")+'</div>');out+='</div>';return out}
function renderTable(data){if(!data.length){$("#breadcrumbs").innerHTML="";$("#detail").innerHTML="";$("#tablewrap").innerHTML='<div class="empty">Keine passenden Datensätze gefunden.</div>';return}const preferred={players:["pass_number","name","current_club_id","current_association_id","identity_status"],clubs:["canonical_name","normalized_name"],associations:["association_name","abbreviation"],tournaments:["date","tournament_name","location"],results:["player_id","tournament_id","position","total_score"],rounds:["result_id","round_no","score"],drl:["player_id","pass_number","rank","value"],dmv:["player_id","year","category"]}[state.view]||[];const all=[...new Set(data.flatMap(Object.keys))];const cols=[...preferred.filter(k=>data.some(o=>k in o)),...all.filter(k=>!preferred.includes(k))].slice(0,8);let h="<div class='tablebox'><table><thead><tr>"+cols.map(k=>"<th>"+esc(k)+"</th>").join("")+"</tr></thead><tbody>";h+=data.slice(0,500).map(o=>"<tr>"+cols.map(k=>"<td>"+cell(o,k)+"</td>").join("")+"</tr>").join("");h+="</tbody></table></div>";if(data.length>500)h+='<div class="note">Anzeige auf 500 Datensätze begrenzt. Suche zur Eingrenzung verwenden.</div>';$("#breadcrumbs").innerHTML="";$("#detail").innerHTML="";$("#tablewrap").innerHTML=h}
function renderDetail(){const o=findById(state.view,state.detail);if(!o){$("#detail").innerHTML='<div class="empty">Datensatz nicht gefunden.</div>';$("#tablewrap").innerHTML="";return}$("#breadcrumbs").innerHTML=link(state.view,state.detail,"← Übersicht")+" · "+esc(label(o));if(state.view==="players"){$("#detail").innerHTML=playerDetail(o);$("#tablewrap").innerHTML="";return}const entries=Object.entries(o).filter(([,v])=>v!=="");$("#detail").innerHTML='<div class="cards">'+entries.slice(0,18).map(([k,v])=>'<div class="card"><small>'+esc(k)+'</small><strong>'+esc(v)+'</strong></div>').join("")+"</div>";const maps={clubs:[["players","Spieler"],["tournaments","Turniere"],["results","Ergebnisse"]],tournaments:[["players","Spieler"],["results","Ergebnisse"],["rounds","Runden"]],results:[["players","Spieler"],["tournaments","Turnier"],["rounds","Runden"]]};let blocks="";for(const [v,l] of maps[state.view]||[]){const rr=related(v,o);if(rr.length)blocks+='<div class="card rel"><small>'+l+"</small><strong>"+rr.length.toLocaleString("de-DE")+" Treffer</strong><div>"+rr.slice(0,15).map(x=>link(v,ident(x),label(x))).join(" · ")+"</div></div>"}$("#tablewrap").innerHTML=blocks||'<div class="empty">Keine direkten Verknüpfungen gefunden.</div>'}
function render(){const labels={players:"Spieler",clubs:"Vereine",associations:"Verbände",tournaments:"Turniere",results:"Ergebnisse",rounds:"Runden",drl:"DRL-Listen",dmv:"DMV-Daten"};$("#viewLabel").textContent=labels[state.view]||state.view;$("#title").textContent=state.detail?"Detailansicht":$("#viewLabel").textContent+"übersicht";const data=(DATA[state.view]||[]).filter(matches);$("#count").textContent=(state.detail?1:data.length).toLocaleString("de-DE")+" Datensätze";renderStats();state.detail?renderDetail():renderTable(data)}
$("#search").addEventListener("input",e=>{state.q=e.target.value;state.detail=null;render()});$("#clear").onclick=()=>{state.q="";$("#search").value="";state.detail=null;render()};document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>setView(b.dataset.view));$("#themeBtn").onclick=()=>document.body.classList.toggle("light");Promise.all(Object.keys(SOURCES).map(load)).then(()=>loadDRL()).then(render);