const DATA={players:[],clubs:[],tournaments:[],results:[],drl:[],dmv:[]};let state={view:"players",q:"",detail:null};
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function load(path,key){try{const r=await fetch(path);if(!r.ok)throw 0;const t=await r.text();DATA[key]=t.trim()?parseCSV(t):[]}catch(e){DATA[key]=[]}}
function parseCSV(t){const rows=[];let row=[],cell="",q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===","&&!q){row.push(cell);cell="";continue}if((c==="\n"||c==="\r")&&!q){if(c==="\r"&&n==="\n")i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell="";continue}cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const h=rows.shift().map(x=>x.trim());return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??"").trim()])))} 
function val(o,...keys){for(const k of keys)if(o&&o[k]!=null&&o[k]!=="")return o[k];return ""}
function id(o){return val(o,"player_id","club_id","tournament_id","result_id","drl_entry_id","dmv_entry_id","id")}
function nameOf(o){return val(o,"name","canonical_name","original_name","tournament_name","club_name","original_club")}
function match(o){const q=state.q.toLocaleLowerCase("de-DE");return !q||Object.values(o).some(v=>String(v).toLocaleLowerCase("de-DE").includes(q))}
function setView(v){state.view=v;state.detail=null;document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));render()}
function link(view,key,label){return '<button class="link" onclick="openItem(\''+view+'\',\''+String(key).replace(/'/g,"\\'")+'\')">'+esc(label||key)+'</button>'}
function openItem(view,key){state.view=view;state.detail=key;state.q="";$("#search").value="";render()}
function related(v,key){const arr=DATA[v]||[];return arr.filter(o=>Object.values(o).some(x=>String(x)===String(key)))} 
function render(){const data=(DATA[state.view]||[]).filter(match);$("#viewLabel").textContent={players:"Spieler",clubs:"Vereine",tournaments:"Turniere",results:"Ergebnisse",drl:"DRL-Listen",dmv:"DMV-Daten"}[state.view];$("#title").textContent=state.detail?"Detailansicht":$("#viewLabel").textContent+"übersicht";$("#count").textContent=data.length+" Datensätze";renderStats();if(state.detail)renderDetail();else renderTable(data)}
function renderStats(){const s=[["6.438","Spieler"],["402","Vereine"],["963","Turniere"],["52.915","Ergebnisse"]];$("#stats").innerHTML=s.map(x=>'<div class="stat"><b>'+x[0]+'</b><span>'+x[1]+"</span></div>").join("")}
function renderTable(data){if(!data.length){$("#tablewrap").innerHTML='<div class="empty">Keine passenden Datensätze gefunden.</div>';return}const keys=[...new Set(data.flatMap(Object.keys))].slice(0,8);let h="<div class='tablebox'><table><thead><tr>"+keys.map(k=>"<th>"+esc(k)+"</th>").join("")+"</tr></thead><tbody>";h+=data.slice(0,250).map(o=>"<tr>"+keys.map(k=>"<td>"+esc(val(o,k))+"</td>").join("")+"</tr>").join("");h+="</tbody></table></div>";$("#tablewrap").innerHTML=h}
function renderDetail(){const arr=DATA[state.view]||[],o=arr.find(x=>String(id(x))===String(state.detail));if(!o){$("#detail").innerHTML='<div class="empty">Datensatz nicht gefunden.</div>';$("#tablewrap").innerHTML="";return}const main=Object.entries(o).filter(([k,v])=>v!=="").slice(0,14);$("#breadcrumbs").innerHTML='<button onclick="setView(\''+state.view+'\')">← Übersicht</button> · '+esc(nameOf(o)||id(o));$("#detail").innerHTML='<div class="cards">'+main.map(([k,v])=>'<div class="card"><small>'+esc(k)+'</small><strong>'+esc(v)+'</strong></div>').join("")+"</div>";let blocks="";const pid=id(o);for(const [v,label] of Object.entries({results:"Ergebnisse",drl:"DRL-Einträge",dmv:"DMV-Einträge"})){const rr=related(v,pid);if(rr.length)blocks+='<div class="card" style="margin-top:12px"><small>'+label+'</small><strong>'+rr.length+' Treffer</strong><button class="link" onclick="setView(\''+v+'\')">Öffnen</button></div>'}$("#tablewrap").innerHTML=blocks}
$("#search").addEventListener("input",e=>{state.q=e.target.value;state.detail=null;render()});$("#clear").onclick=()=>{$("#search").value="";state.q="";state.detail=null;render()};document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>setView(b.dataset.view));$("#themeBtn").onclick=()=>document.body.classList.toggle("light");
Promise.all([["data/players.csv","players"],["data/clubs.csv","clubs"],["data/tournaments.csv","tournaments"],["data/results.csv","results"],["data/drl_entries.csv","drl"],["data/dmv_entries.csv","dmv"]].map(x=>load(...x))).then(render);